import { DeployFunction } from "hardhat-deploy/types";
import { HardhatRuntimeEnvironment } from "hardhat/types";
import fs from "fs";
import path from "path";

const func: DeployFunction = async function (hre: HardhatRuntimeEnvironment) {
  const { deployer } = await hre.getNamedAccounts();
  const { deploy } = hre.deployments;

  const deployed = await deploy("SecretSwap", {
    from: deployer,
    log: true,
  });

  console.log(`SecretSwap contract: `, deployed.address);

  if (hre.network.name === "sepolia") {
    const frontendContractsPath = path.resolve(__dirname, "..", "frontend", "src", "config", "contracts.ts");
    const contents = `// SecretSwap contract deployed on Sepolia.\n// This file is auto-generated by hardhat-deploy (deploy/01_secretSwap.ts).\nexport const CONTRACT_ADDRESS = '${deployed.address}';\n\nexport const CONTRACT_ABI = ${JSON.stringify(
      deployed.abi,
      null,
      2,
    )} as const;\n`;
    fs.writeFileSync(frontendContractsPath, contents, "utf8");
    console.log(`Updated frontend contract config: ${frontendContractsPath}`);
  }
};

export default func;
func.id = "deploy_secretSwap";
func.tags = ["SecretSwap"];
